/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controller.SnmpController;
import javax.swing.JOptionPane;

/**
 *
 * @author PEDRO
 */
public class SnmpGUI extends javax.swing.JFrame {

    SnmpController controller;

    /**
     * Creates new form SnmpGUI
     */
    public SnmpGUI() {
        controller = new SnmpController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        consolePanel = new javax.swing.JPanel();
        consoleScrollPane = new javax.swing.JScrollPane();
        consoleTextArea = new javax.swing.JTextArea();
        ipPanel = new javax.swing.JPanel();
        ipAddrLabel = new javax.swing.JLabel();
        ipTextField = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        netDiscButton = new javax.swing.JButton();
        connectedToLabel = new javax.swing.JLabel();
        connectedIpLabel = new javax.swing.JLabel();
        communiy1Label = new javax.swing.JLabel();
        community1TextField = new javax.swing.JTextField();
        functionsPanel = new javax.swing.JTabbedPane();
        getPanel = new javax.swing.JPanel();
        getButton = new javax.swing.JButton();
        getObjectLabel = new javax.swing.JLabel();
        getObjectComboBox = new javax.swing.JComboBox();
        getCommunityLabel = new javax.swing.JLabel();
        getCommunityTextField = new javax.swing.JTextField();
        getnextPanel = new javax.swing.JPanel();
        getNextButton = new javax.swing.JButton();
        getNextObjectLabel = new javax.swing.JLabel();
        getNextObjectComboBox = new javax.swing.JComboBox();
        getNextCommunityLabel = new javax.swing.JLabel();
        getNextCommunityTextField = new javax.swing.JTextField();
        setPanel = new javax.swing.JPanel();
        SetButton = new javax.swing.JButton();
        setObjectLabel = new javax.swing.JLabel();
        setObjectComboBox = new javax.swing.JComboBox();
        setCommunityLabel = new javax.swing.JLabel();
        setCommunityTextField = new javax.swing.JTextField();
        setNewValueLabel = new javax.swing.JLabel();
        setNewValueTextField = new javax.swing.JTextField();
        getbulkPanel = new javax.swing.JPanel();
        walkPanel = new javax.swing.JPanel();
        gettablePanel = new javax.swing.JPanel();
        getdeltaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        consolePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Console"));

        consoleTextArea.setEditable(false);
        consoleTextArea.setColumns(20);
        consoleTextArea.setRows(5);
        consoleScrollPane.setViewportView(consoleTextArea);

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consoleScrollPane)
                .addContainerGap())
        );
        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consoleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        ipPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel"));

        ipAddrLabel.setText("IP Address:");

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        netDiscButton.setText("Network Discovery");
        netDiscButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netDiscButtonActionPerformed(evt);
            }
        });

        connectedToLabel.setText("Connected to:");

        connectedIpLabel.setText("not connected yet.");

        communiy1Label.setText("Community:");

        community1TextField.setText("public");

        javax.swing.GroupLayout ipPanelLayout = new javax.swing.GroupLayout(ipPanel);
        ipPanel.setLayout(ipPanelLayout);
        ipPanelLayout.setHorizontalGroup(
            ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ipPanelLayout.createSequentialGroup()
                        .addComponent(connectedToLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectedIpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ipPanelLayout.createSequentialGroup()
                        .addGroup(ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ipPanelLayout.createSequentialGroup()
                                .addComponent(communiy1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(netDiscButton)
                                    .addComponent(community1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ipPanelLayout.createSequentialGroup()
                                .addComponent(ipAddrLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(connectButton)))
                .addContainerGap())
        );
        ipPanelLayout.setVerticalGroup(
            ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ipPanelLayout.createSequentialGroup()
                .addGroup(ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ipPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ipAddrLabel)
                            .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(communiy1Label)
                            .addComponent(community1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ipPanelLayout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addComponent(netDiscButton)
                .addGap(18, 18, 18)
                .addGroup(ipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectedToLabel)
                    .addComponent(connectedIpLabel))
                .addContainerGap())
        );

        functionsPanel.setPreferredSize(new java.awt.Dimension(362, 156));

        getPanel.setPreferredSize(new java.awt.Dimension(291, 90));

        getButton.setText("GET");
        getButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getButtonActionPerformed(evt);
            }
        });

        getObjectLabel.setText("Object:");

        getObjectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sysDescr", "sysUpTime", "sysContact", "sysName", "sysLocation", "ifNumber", "ifTable", "ipInReceives", "ipOutRequests", "ipRouteTable", "tcpInSegs", "tcpOutSegs", "tcpConnTable", "udpInDatagrams", "udpOutDatagrams", "udpTable", "icmpInMsgs", "icmpInEchoReps", "icmpOutMsgs", "snmpInPkts", "snmpOutPkts", "snmpInBadCommunityName", "snmpInGetRequests", "snmpInGetNexts", "snmpInSetRequests", "snmpInGetResponses", "snmpOutGetRequests", "snmpOutGetNexts", "snmpOutSetRequests", "snmpOutGetResponses" }));

        getCommunityLabel.setText("Community:");

        getCommunityTextField.setText("public");

        javax.swing.GroupLayout getPanelLayout = new javax.swing.GroupLayout(getPanel);
        getPanel.setLayout(getPanelLayout);
        getPanelLayout.setHorizontalGroup(
            getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(getPanelLayout.createSequentialGroup()
                        .addComponent(getCommunityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getCommunityTextField))
                    .addGroup(getPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(getObjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getObjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        getPanelLayout.setVerticalGroup(
            getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getPanelLayout.createSequentialGroup()
                .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(getPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getCommunityLabel)
                            .addComponent(getCommunityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(getPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getObjectLabel)
                            .addComponent(getObjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(getPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(getButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        functionsPanel.addTab("GET", getPanel);

        getNextButton.setText("GETNEXT");
        getNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNextButtonActionPerformed(evt);
            }
        });

        getNextObjectLabel.setText("Object:");

        getNextObjectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sysDescr", "sysUpTime", "sysContact", "sysName", "sysLocation", "ifNumber", "ifTable", "ipInReceives", "ipOutRequests", "ipRouteTable", "tcpInSegs", "tcpOutSegs", "tcpConnTable", "udpInDatagrams", "udpOutDatagrams", "udpTable", "icmpInMsgs", "icmpInEchoReps", "icmpOutMsgs", "snmpInPkts", "snmpOutPkts", "snmpInBadCommunityName", "snmpInGetRequests", "snmpInGetNexts", "snmpInSetRequests", "snmpInGetResponses", "snmpOutGetRequests", "snmpOutGetNexts", "snmpOutSetRequests", "snmpOutGetResponses" }));
        getNextObjectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getNextObjectComboBoxActionPerformed(evt);
            }
        });

        getNextCommunityLabel.setText("Community:");

        getNextCommunityTextField.setText("public");

        javax.swing.GroupLayout getnextPanelLayout = new javax.swing.GroupLayout(getnextPanel);
        getnextPanel.setLayout(getnextPanelLayout);
        getnextPanelLayout.setHorizontalGroup(
            getnextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getnextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(getnextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(getnextPanelLayout.createSequentialGroup()
                        .addComponent(getNextCommunityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getNextCommunityTextField))
                    .addGroup(getnextPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(getNextObjectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getNextObjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getNextButton)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        getnextPanelLayout.setVerticalGroup(
            getnextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getnextPanelLayout.createSequentialGroup()
                .addGroup(getnextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(getnextPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(getnextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getNextCommunityLabel)
                            .addComponent(getNextCommunityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(getnextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getNextObjectLabel)
                            .addComponent(getNextObjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(getnextPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(getNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        functionsPanel.addTab("GETNEXT", getnextPanel);

        SetButton.setText("SET");
        SetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetButtonActionPerformed(evt);
            }
        });

        setObjectLabel.setText("Object:");

        setObjectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "sysDescr", "sysUpTime", "sysContact", "sysName", "sysLocation", "ifNumber", "ifTable", "ipInReceives", "ipOutRequests", "ipRouteTable", "tcpInSegs", "tcpOutSegs", "tcpConnTable", "udpInDatagrams", "udpOutDatagrams", "udpTable", "icmpInMsgs", "icmpInEchoReps", "icmpOutMsgs", "snmpInPkts", "snmpOutPkts", "snmpInBadCommunityName", "snmpInGetRequests", "snmpInGetNexts", "snmpInSetRequests", "snmpInGetResponses", "snmpOutGetRequests", "snmpOutGetNexts", "snmpOutSetRequests", "snmpOutGetResponses" }));

        setCommunityLabel.setText("Community:");

        setCommunityTextField.setText("public");

        setNewValueLabel.setText("New value: ");

        javax.swing.GroupLayout setPanelLayout = new javax.swing.GroupLayout(setPanel);
        setPanel.setLayout(setPanelLayout);
        setPanelLayout.setHorizontalGroup(
            setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setPanelLayout.createSequentialGroup()
                        .addGroup(setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(setPanelLayout.createSequentialGroup()
                                .addComponent(setCommunityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setCommunityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(setPanelLayout.createSequentialGroup()
                                .addComponent(setNewValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(setNewValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(setPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(setObjectLabel)
                        .addGap(23, 23, 23)
                        .addComponent(setObjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(SetButton)
                        .addGap(21, 21, 21))))
        );
        setPanelLayout.setVerticalGroup(
            setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setCommunityLabel)
                    .addComponent(setCommunityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setObjectLabel)
                    .addComponent(setObjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(setPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setNewValueLabel)
                    .addComponent(setNewValueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        functionsPanel.addTab("SET", setPanel);

        javax.swing.GroupLayout getbulkPanelLayout = new javax.swing.GroupLayout(getbulkPanel);
        getbulkPanel.setLayout(getbulkPanelLayout);
        getbulkPanelLayout.setHorizontalGroup(
            getbulkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        getbulkPanelLayout.setVerticalGroup(
            getbulkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        functionsPanel.addTab("GETBULK", getbulkPanel);

        javax.swing.GroupLayout walkPanelLayout = new javax.swing.GroupLayout(walkPanel);
        walkPanel.setLayout(walkPanelLayout);
        walkPanelLayout.setHorizontalGroup(
            walkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        walkPanelLayout.setVerticalGroup(
            walkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        functionsPanel.addTab("WALK", walkPanel);

        javax.swing.GroupLayout gettablePanelLayout = new javax.swing.GroupLayout(gettablePanel);
        gettablePanel.setLayout(gettablePanelLayout);
        gettablePanelLayout.setHorizontalGroup(
            gettablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        gettablePanelLayout.setVerticalGroup(
            gettablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        functionsPanel.addTab("GETTABLE", gettablePanel);

        javax.swing.GroupLayout getdeltaPanelLayout = new javax.swing.GroupLayout(getdeltaPanel);
        getdeltaPanel.setLayout(getdeltaPanelLayout);
        getdeltaPanelLayout.setHorizontalGroup(
            getdeltaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
        );
        getdeltaPanelLayout.setVerticalGroup(
            getdeltaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        functionsPanel.addTab("GETDELTA", getdeltaPanel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(consolePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addComponent(ipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(functionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(functionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consolePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        functionsPanel.getAccessibleContext().setAccessibleName("tab");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getButtonActionPerformed
        if(!connectedIpLabel.getText().equals("not connected yet.")) {
            String objectOid = controller.translateObjectToOID(getObjectComboBox.getSelectedItem().toString());
            consoleTextArea.setText(controller.snmpFunctionsToString(this.getCommunityTextField.getText(), this.getButton.getText(), objectOid, this.connectedIpLabel.getText(), ""));
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum agente encontra-se conectado no momento.", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_getButtonActionPerformed

    private void netDiscButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netDiscButtonActionPerformed
        String agents = controller.networkDiscoveryToString(this.community1TextField.getText());
        consoleTextArea.setText(agents);
    }//GEN-LAST:event_netDiscButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        boolean redundant = this.ipTextField.getText().equals(this.connectedIpLabel.getText());
        boolean isAgent = controller.isAgent(this.community1TextField.getText(), this.ipTextField.getText());
        if (!redundant && isAgent) {
            consoleTextArea.setText("Conectado a " + ipTextField.getText());
            connectedIpLabel.setText(ipTextField.getText());
        } else if(redundant && isAgent) {
            JOptionPane.showMessageDialog(this, "O agente especificado já encontra-se conectado.", "Inane error", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Informações não representam um agente SNMP válido.", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void getNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNextButtonActionPerformed
        if(!connectedIpLabel.getText().equals("not connected yet.")) {
            String objectOid = controller.translateObjectToOID(getNextObjectComboBox.getSelectedItem().toString());
            consoleTextArea.setText(controller.snmpFunctionsToString(this.community1TextField.getText(), this.getNextButton.getText(), objectOid, this.connectedIpLabel.getText(), ""));
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum agente encontra-se conectado no momento.", "Inane error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_getNextButtonActionPerformed

    private void getNextObjectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getNextObjectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getNextObjectComboBoxActionPerformed

    private void SetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetButtonActionPerformed
     if(!connectedIpLabel.getText().equals("not connected yet.")) {
            String objectOid = controller.translateObjectToOID(getNextObjectComboBox.getSelectedItem().toString());
            consoleTextArea.setText(controller.snmpFunctionsToString(this.community1TextField.getText(), this.getNextButton.getText(), objectOid, this.connectedIpLabel.getText(), this.setNewValueTextField.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum agente encontra-se conectado no momento.", "Inane error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_SetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnmpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SnmpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SetButton;
    private javax.swing.JTextField community1TextField;
    private javax.swing.JLabel communiy1Label;
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel connectedIpLabel;
    private javax.swing.JLabel connectedToLabel;
    private javax.swing.JPanel consolePanel;
    private javax.swing.JScrollPane consoleScrollPane;
    private javax.swing.JTextArea consoleTextArea;
    private javax.swing.JTabbedPane functionsPanel;
    private javax.swing.JButton getButton;
    private javax.swing.JLabel getCommunityLabel;
    private javax.swing.JTextField getCommunityTextField;
    private javax.swing.JButton getNextButton;
    private javax.swing.JLabel getNextCommunityLabel;
    private javax.swing.JTextField getNextCommunityTextField;
    private javax.swing.JComboBox getNextObjectComboBox;
    private javax.swing.JLabel getNextObjectLabel;
    private javax.swing.JComboBox getObjectComboBox;
    private javax.swing.JLabel getObjectLabel;
    private javax.swing.JPanel getPanel;
    private javax.swing.JPanel getbulkPanel;
    private javax.swing.JPanel getdeltaPanel;
    private javax.swing.JPanel getnextPanel;
    private javax.swing.JPanel gettablePanel;
    private javax.swing.JLabel ipAddrLabel;
    private javax.swing.JPanel ipPanel;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton netDiscButton;
    private javax.swing.JLabel setCommunityLabel;
    private javax.swing.JTextField setCommunityTextField;
    private javax.swing.JLabel setNewValueLabel;
    private javax.swing.JTextField setNewValueTextField;
    private javax.swing.JComboBox setObjectComboBox;
    private javax.swing.JLabel setObjectLabel;
    private javax.swing.JPanel setPanel;
    private javax.swing.JPanel walkPanel;
    // End of variables declaration//GEN-END:variables
}
